on:
  push:
    branches:
      - main
  release:
    types:
      - created

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn
      - name: Publish
        run: yarn deploy
        env:
          VSCE_PAT: ${{ secrets.MARKETPLACE_PAT }}
